# Site settings
title: Measure Zero
email: billyanhuang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of short posts on things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://byh1997.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
